api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    elasticsearch:
        hosts: ['%env(ELASTICSEARCH_HOST)%']
        mapping:
            App\Entity\Bookmark:
                index: bookmarks
                type: bookmark
